import { Link } from "react-router-dom";
import { LandingNav } from "./Landing";

function Block({ h, children }: { h: string; children: React.ReactNode }) {
  return (
    <>
      <h3>{h}</h3>
      {children}
    </>
  );
}

function Privacy() {
  return (
    <div className="legal-prose">
      <Block h="1. Overview">
        <p>
          This Privacy Policy explains how Aurex ("we", "our", "us") collects, uses, and protects
          information when you use the Aurex platform (the "Service"). By using the Service you
          agree to the practices described here.
        </p>
      </Block>

      <Block h="2. Information we collect">
        <p>We collect only what is necessary to operate the Service:</p>
        <ul>
          <li>
            <strong>Account information.</strong> When you sign in with Google, we receive your
            name, email address, and profile picture from Google solely to create and identify your
            account.
          </li>
          <li>
            <strong>Content you create.</strong> Projects, task descriptions, prompts, messages, and
            the files, runs, and output generated by the agents inside your private workspace.
          </li>
          <li>
            <strong>Session data.</strong> A signed, secure session cookie that keeps you signed in.
            We do not use third-party trackers or advertising cookies.
          </li>
          <li>
            <strong>Usage & diagnostics.</strong> Basic server logs (such as timestamps and error
            messages) used to keep the Service running and secure.
          </li>
        </ul>
      </Block>

      <Block h="3. How we use information">
        <ul>
          <li>To create and manage your account and your private workspace.</li>
          <li>To execute, stream, and store your agent runs and their results.</li>
          <li>To provide previews, publishing, and code export for your projects.</li>
          <li>To operate, secure, and improve the Service.</li>
        </ul>
        <p>We do not sell your personal information and we do not use it for advertising.</p>
      </Block>

      <Block h="4. Privacy and isolation">
        <p>
          Your workspaces are isolated: each account gets its own private container, and access is
          enforced at the API level so no other user can list, read, or modify your projects, runs,
          or files. Unless you choose to publish a project, your content is never visible to other
          users.
        </p>
      </Block>

      <Block h="5. Data retention">
        <p>
          Your projects and run history remain stored while your account is active. You may delete a
          project at any time, which removes its workspace, files, and run history. When you delete
          your account, we will remove the data we hold about you within a reasonable period, except
          where we are required to retain it for legal, security, or billing purposes.
        </p>
      </Block>

      <Block h="6. Security">
        <p>
          We use industry-standard measures to protect your data, including encrypted transport
          (HTTPS), signed session cookies, API-enforced access controls, and operating-system-level
          isolation between workspaces. No method of transmission or storage is 100% secure, and we
          cannot guarantee absolute security.
        </p>
      </Block>

      <Block h="7. Third-party services">
        <p>
          Sign-in is provided through Google OAuth. Google receives the information you authorize
          them to share (your profile name, email, and avatar). Your use of Google's services is
          governed by Google's own privacy policy.
        </p>
      </Block>

      <Block h="8. Children">
        <p>
          The Service is not directed to children under 16, and we do not knowingly collect
          information from children. If you believe a child has provided us with personal
          information, please contact us and we will delete it.
        </p>
      </Block>

      <Block h="9. Changes to this policy">
        <p>
          We may update this policy from time to time. Material changes will be noted on this page.
          Your continued use of the Service after changes constitutes acceptance of the updated
          policy.
        </p>
      </Block>

      <Block h="10. Contact">
        <p>
          Questions about this policy? Contact us at{" "}
          <a href="mailto:support@aurex.ai">support@aurex.ai</a>.
        </p>
      </Block>
    </div>
  );
}

function Terms() {
  return (
    <div className="legal-prose">
      <Block h="1. Acceptance of terms">
        <p>
          These Terms of Service ("Terms") govern your access to and use of the Aurex platform (the
          "Service"). By creating an account or using the Service, you agree to these Terms. If you
          do not agree, you must not use the Service.
        </p>
      </Block>

      <Block h="2. The Service">
        <p>
          Aurex provides autonomous AI agents that work inside private, isolated Linux workspaces.
          You direct agents by describing tasks; agents may create, modify, and delete files, run
          commands, and produce output inside your workspace. The Service includes a live session
          console, file browsing, app previews, and optional publishing.
        </p>
      </Block>

      <Block h="3. Accounts">
        <p>
          You must provide accurate account information. You are responsible for safeguarding your
          credentials and for all activity that occurs under your account. Notify us promptly of any
          unauthorized use. We may suspend or terminate accounts that violate these Terms.
        </p>
      </Block>

      <Block h="4. Acceptable use">
        <p>You agree not to use the Service to:</p>
        <ul>
          <li>Violate any applicable law or regulation.</li>
          <li>Infringe the intellectual property or other rights of others.</li>
          <li>Distribute malware, phishing, or other harmful content.</li>
          <li>Attempt to access other users' workspaces, data, or systems.</li>
          <li>Probe, scan, or test the security of the Service without authorization.</li>
          <li>Use the Service to generate content intended to harass or harm others.</li>
        </ul>
      </Block>

      <Block h="5. Your content and AI output">
        <p>
          You retain all rights to the content you provide and the output your agents produce in
          your workspace. You are solely responsible for that content, including ensuring you have
          the right to use it. By using the Service, you grant us a limited license to process and
          store your content solely to provide the Service to you.
        </p>
        <p>
          AI-generated output may be inaccurate, incomplete, or unsuitable for your purposes. You
          are responsible for reviewing and validating any output before relying on it, including
          before deployment, publication, or distribution.
        </p>
      </Block>

      <Block h="6. Pricing and payment">
        <p>
          The Service is offered on a free tier ("Free Forever") and may include paid plans in the
          future. Free-tier accounts include a private workspace, community models, and standard
          limits on run duration and resources. Where paid features are offered, pricing will be
          stated at the point of purchase and payable in advance unless otherwise agreed.
        </p>
      </Block>

      <Block h="7. Intellectual property">
        <p>
          The Service, including its software, design, and branding, is owned by Aurex and
          protected by intellectual property laws. You may not copy, modify, distribute, sell, or
          reverse-engineer the Service except as permitted by law.
        </p>
      </Block>

      <Block h="8. Limitation of liability">
        <p>
          To the maximum extent permitted by law, Aurex shall not be liable for any indirect,
          incidental, special, or consequential damages, or for any loss of data, profits, or
          business opportunities, arising out of or related to your use of the Service. Our total
          liability for any claim shall not exceed the amounts you paid us in the twelve months
          preceding the claim.
        </p>
      </Block>

      <Block h="9. Disclaimer of warranties">
        <p>
          The Service is provided "as is" and "as available" without warranties of any kind, whether
          express or implied, including merchantability, fitness for a particular purpose, and
          non-infringement. We do not warrant that the Service will be uninterrupted, error-free, or
          that agent output will be accurate.
        </p>
      </Block>

      <Block h="10. Termination">
        <p>
          You may stop using the Service at any time. We may suspend or terminate your access if you
          breach these Terms or where required by law. Upon termination, your right to use the
          Service ends; we will delete your data as described in our Privacy Policy.
        </p>
      </Block>

      <Block h="11. Changes to the Terms">
        <p>
          We may update these Terms from time to time. We will post updated Terms on this page with
          a revised date. Continued use of the Service after changes constitutes acceptance.
        </p>
      </Block>

      <Block h="12. Governing law">
        <p>
          These Terms are governed by the laws of the jurisdiction in which Aurex is established,
          without regard to conflict-of-law principles, and any disputes shall be resolved in the
          courts of that jurisdiction.
        </p>
      </Block>

      <Block h="13. Contact">
        <p>
          Questions about these Terms? Contact us at{" "}
          <a href="mailto:support@aurex.ai">support@aurex.ai</a>.
        </p>
      </Block>
    </div>
  );
}

const META: Record<string, { title: string; updated: string }> = {
  privacy: { title: "Privacy Policy", updated: "August 14, 2026" },
  terms: { title: "Terms of Service", updated: "August 14, 2026" },
};

export default function LegalPage({ kind }: { kind: "privacy" | "terms" }) {
  const meta = META[kind];
  return (
    <div className="landing">
      <LandingNav />
      <div className="legal-page">
        <div className="breadcrumb">
          <Link to="/">Home</Link>
          <span>›</span>
          <span>{meta.title}</span>
        </div>
        <div className="legal-head">
          <span className="eyebrow">Legal</span>
          <h1>{meta.title}</h1>
          <p className="muted">Last updated: {meta.updated}</p>
        </div>
        <div className="card legal-card">
          {kind === "privacy" ? <Privacy /> : <Terms />}
        </div>
      </div>
    </div>
  );
}
